#!/usr/bin/env bash

function _kibana_profile {
  local shome="${_kibana_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/exec:$PATH"
  export kibana_version="4.5.1"
}

_kibana_profile
